#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RaysHotDogs.Droid.Resource", IsApplication=true)]

namespace RaysHotDogs.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cinnabar = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FavoritesIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int MeatLoversIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RayLogo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int VeggieLoversIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int aboutButton = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int amoutEditText = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int callTextView = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int cancelButton = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int cartButton = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int descriptionTextView = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int fragmentContainer = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int hotDogDetailImage = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int hotDogImageView = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int hotDogListView = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int hotDogNameTextView = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int logoImageView = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int mainScrollView = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int mapButton = 2131165202;
			
			// aapt resource value: 0x7f07000b
			public const int orderButton = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int phoneNumberTextView = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int pictureWithRay = 2131165205;
			
			// aapt resource value: 0x7f070007
			public const int priceTextView = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int relativeLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int shortDescriptionTextView = 2131165189;
			
			// aapt resource value: 0x7f070016
			public const int takePicture = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int takePictureButton = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int textView1 = 2131165204;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HotDogDetailView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HotDogListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HotDogMenuView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HotDogRowView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenuView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TakePictureView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CodeFont = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
