#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RaysHotDogs.Droid.Resource", IsApplication=true)]

namespace RaysHotDogs.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cinnabar = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FavoritesIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int MeatLoversIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RayLogo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int VeggieLoversIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int aboutButton = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int amoutEditText = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int callTextView = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int cancelButton = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int cartButton = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int descriptionTextView = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int fragmentContainer = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int hotDogDetailImage = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int hotDogImageView = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int hotDogListView = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int hotDogNameTextView = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int logoImageView = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int mainScrollView = 2131099650;
			
			// aapt resource value: 0x7f060012
			public const int mapButton = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int orderButton = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int phoneNumberTextView = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int priceTextView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int relativeLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int shortDescriptionTextView = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int takePictureButton = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HotDogDetailView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HotDogListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HotDogMenuView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HotDogRowView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenuView = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
